Controllers/BsVendorController.cs
using System;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using Nop.Core;
using Nop.Core.Domain.Orders;
using Nop.Services.Catalog;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Orders;
using Nop.Services.Stores;
using Nop.Services.Seo;
using Nop.Web.Framework.Controllers;
using Nop.Core.Domain.Customers;
using Nop.Web.Infrastructure.Cache;
using Nop.Core.Caching;
using Nop.Services.Media;
using Nop.Web.Models.Media;
using Nop.Web.Models.Common;
using System.Collections.Generic;
using Nop.Core.Domain.Common;
using Nop.Core.Domain.Localization;
using Nop.Core.Domain.Vendors;
using Nop.Plugin.Bs.VendorSystem.Domain;
using Nop.Plugin.Bs.VendorSystem.Extension;
using Nop.Plugin.Bs.VendorSystem.Models;
using Nop.Plugin.Bs.VendorSystem.Service;
using Nop.Services.Authentication;
using Nop.Services.Common;
using Nop.Services.Customers;
using Nop.Services.Messages;
using Nop.Services.Vendors;
using Nop.Web.Framework.Kendoui;
using Nop.Admin.Models.Catalog;
using Nop.Services.Shipping;
using Nop.Services.Security;
using Nop.Core.Domain.Catalog;
using Nop.Web.Framework;
using Nop.Services.Directory;
using Nop.Core.Domain.Directory;
using Nop.Services.Helpers;
using Nop.Services.Tax;
using Nop.Services.Discounts;
using Nop.Core.Domain.Discounts;
using Nop.Admin.Extensions;
using Nop.Web.Framework.Mvc;
using Nop.Admin.Models.Orders;
using Nop.Core.Domain.Payments;
using Nop.Core.Domain.Shipping;
using Nop.Services.Payments;
using Nop.Core.Domain.Tax;
using System.IO;
using System.Web.Routing;
using Nop.Admin.Controllers;
using Nop.Core.Domain.Media;
using Nop.Core.Infrastructure;
using Nop.Web.Framework.Security;
using Nop.Web.Models.Catalog;


namespace Nop.Plugin.Bs.VendorSystem.Controllers
{
    public class BsVendorController : BasePluginController
    {
        private readonly IWorkContext _workContext;
        private readonly IStoreContext _storeContext;
        private readonly IBsVendorService _bsVendorService;
        private readonly ICustomerService _customerService;
        private readonly CustomerSettings _customerSettings;
        private readonly ICustomerRegistrationService _customerRegistrationService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly IAddressService _addressService;
        private readonly IWorkflowMessageService _workflowMessageService;
        private readonly LocalizationSettings _localizationSettings;
        private readonly IVendorService _vendorService;
        private readonly IUrlRecordService _urlRecordService;
        private readonly VendorSettings _vendorSettings;
        private readonly IAuthenticationService _authenticationService;
        private readonly ILocalizationService _localizationService;

        private readonly IProductService _productService;
        private readonly IProductTemplateService _productTemplateService;
        private readonly AdminAreaSettings _adminAreaSettings;
        private readonly IPictureService _pictureService;
        private readonly ICategoryService _categoryService;
        private readonly IManufacturerService _manufacturerService;
        private readonly IStoreService _storeService;
        private readonly IShippingService _shippingService;
        private readonly IPermissionService _permissionService;
        private readonly ILanguageService _languageService;
        private readonly ICurrencyService _currencyService;
        private readonly CurrencySettings _currencySettings;
        private readonly IMeasureService _measureService;
        private readonly MeasureSettings _measureSettings;
        private readonly IDateTimeHelper _dateTimeHelper;
        private readonly IProductAttributeService _productAttributeService;
        private readonly IShipmentService _shipmentService;
        private readonly ITaxCategoryService _taxCategoryService;
        private readonly ISpecificationAttributeService _specificationAttributeService;
        private readonly IDiscountService _discountService;
        private readonly IAclService _aclService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly IProductTagService _productTagService;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly IProductAttributeFormatter _productAttributeFormatter;
        private readonly IProductAttributeParser _productAttributeParser;
        private readonly IDownloadService _downloadService;


        private readonly IOrderService _orderService;
        private readonly IOrderReportService _orderReportService;
        private readonly IPriceFormatter _priceFormatter;

        private readonly ICountryService _countryService;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly ShippingSettings _shippingSettings;

        private readonly AddressSettings _addressSettings;
        private readonly IGiftCardService _giftCardService;
        private readonly IEncryptionService _encryptionService;
        private readonly IPaymentService _paymentService;
        private readonly TaxSettings _taxSettings;
        private readonly IAddressAttributeFormatter _addressAttributeFormatter;
        private readonly IReturnRequestService _returnRequestService;
        private readonly IPdfService _pdfService;

        private readonly ICacheManager _cacheManager;
        private readonly IWebHelper _webHelper;
        private readonly CatalogSettings _catalogSettings; 
        private readonly IPriceCalculationService _priceCalculationService;
        private readonly ITaxService _taxService;
        private readonly MediaSettings _mediaSettings;
        public BsVendorController(IWorkContext workContext,
            IStoreContext storeContext,
            IBsVendorService bsVendorService,
            ICustomerService customerService,
            CustomerSettings customerSettings,
            ICustomerRegistrationService customerRegistrationService,
            IGenericAttributeService genericAttributeService,
            IAddressService addressService,
            IWorkflowMessageService workflowMessageService,
            LocalizationSettings localizationSettings,
            IVendorService vendorService,
            IUrlRecordService urlRecordService,
            VendorSettings vendorSettings,
            IAuthenticationService authenticationService,
            ILocalizationService localizationService,
            IProductService productService,
            IProductTemplateService productTemplateService,
            AdminAreaSettings adminAreaSettings,
            IPictureService pictureService,
            ICategoryService categoryService,
            IManufacturerService manufacturerService,
            IStoreService storeService,
            IShippingService shippingService,
            IPermissionService permissionService,
            ILanguageService languageService,
            ICurrencyService currencyService,
            CurrencySettings currencySettings,
            IMeasureService measureService,
            MeasureSettings measureSettings,
            IDateTimeHelper dateTimeHelper,
            IProductAttributeService productAttributeService,
            IShipmentService shipmentService,
            ITaxCategoryService taxCategoryService,
            ISpecificationAttributeService specificationAttributeService,
            IDiscountService discountService,
            IAclService aclService,
            ICustomerActivityService customerActivityService,
            ILocalizedEntityService localizedEntityService,
            IProductTagService productTagService,
            IShoppingCartService shoppingCartService,
            IProductAttributeFormatter productAttributeFormatter,
            IProductAttributeParser productAttributeParser,
            IDownloadService downloadService,


            IOrderService orderService,
            IOrderReportService orderReportService,
            IPriceFormatter priceFormatter,


            ICountryService countryService,
            IOrderProcessingService orderProcessingService,
            ShippingSettings shippingSettings,

            AddressSettings addressSettings,
            IGiftCardService giftCardService,
            IEncryptionService encryptionService,
            IPaymentService paymentService,
            TaxSettings taxSettings,
            IReturnRequestService returnRequestService,
            IAddressAttributeFormatter addressAttributeFormatter,
            IPdfService pdfService,
            ICacheManager cacheManager,
            IWebHelper webhelper,
            CatalogSettings catalogSettings,
            IPriceCalculationService priceCalculationService,
            ITaxService taxService,
            MediaSettings mediaSettings)
        {
            this._workContext = workContext;
            this._storeContext = storeContext;
            this._bsVendorService = bsVendorService;
            this._customerService = customerService;
            this._customerSettings = customerSettings;
            this._customerRegistrationService = customerRegistrationService;
            this._genericAttributeService = genericAttributeService;
            this._addressService = addressService;
            this._workflowMessageService = workflowMessageService;
            this._localizationSettings = localizationSettings;
            this._vendorService = vendorService;
            this._urlRecordService = urlRecordService;
            this._vendorSettings = vendorSettings;
            this._authenticationService = authenticationService;
            this._localizationService = localizationService;

            this._productService = productService;
            this._productTemplateService = productTemplateService;
            this._adminAreaSettings = adminAreaSettings;

Views/Notification/Notification.cshtml
@using Nop.Core.Infrastructure
@using Nop.Web.Framework;
@using Nop.Web.Framework.UI;
@using System.Globalization;
@{
    Layout = "~/Administration/Views/Shared/_AdminLayout.cshtml";
    var defaultGridPageSize = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().DefaultGridPageSize;
    var gridPageSizes = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().GridPageSizes;

    //page title
    ViewBag.Title = T("Admin.System.Log").Text;
}
   <table class="adminContent">
    <tr>
        <td>
            <div id="Notification-grid"></div>

            <script>
                    $(document).ready(function() {
                        $("#Notification-grid").kendoGrid({
                            dataSource: {
                                type: "json",
                                transport: {
                                    read: {
                                        url: "@Html.Raw(Url.Action("UnViewNotificationList", "BsVendor"))",
                                        type: "POST",
                                        dataType: "json"
                                    }
                                },
                                schema: {
                                    data: "Data",
                                    total: "Total",
                                    errors: "Errors"
                                },
                                error: function(e) {
                                    display_kendoui_grid_error(e);
                                    // Cancel the changes
                                    this.cancelChanges();
                                },
                                pageSize: @(defaultGridPageSize),
                                serverPaging: true,
                                serverFiltering: true,
                                serverSorting: true
                            },
                            pageable: {
                                refresh: true,
                                pageSizes: [@(gridPageSizes)]
                            },
                            editable: {
                                confirmation: false,
                                mode: "inline"
                            },
                            scrollable: false,
                           // dataBound: onDataBound,
                            columns: [
                               @* {
                                    field: "PictureThumbnailUrl",
                                    title: "@T("Admin.Catalog.Products.Fields.PictureThumbnailUrl")",
                                    template: '<img src="#=PictureThumbnailUrl#" />',
                                    width: 100
                                },*@
                                {
                                    field: "Name",
                                    title: "@T("Admin.Vendors.Fields.Name")",
                                width: 300
                                 },
                                 {
                                     field: "Email",
                                     title: "@T("Admin.Vendors.Fields.Email")",
                                     width: 300
                                  }
                            ]
                        } );
                    });
            </script>
        </td>
    </tr>
</table>

Views/Notification/NotificationHeader.cshtml
@{
    Html.AddCssFileParts("~/Plugins/Bs.VendorSystem/content/Style/Like.css");
    var UnViewNotificationList = Url.RouteUrl("Vendor.UnViewNotificationList");
    var AllNotificationList = Url.RouteUrl("Vendor.AllNotificationList");
    //var urlUnLike = Url.RouteUrl("Widgets.Like.CustomerProductUnLike", new { productId = Model.ProductId });
}
@model BsVendorNotificationCountModel
@using Nop.Core
@using Nop.Core.Domain.Customers
@using Nop.Core.Infrastructure
@using Nop.Plugin.Bs.VendorSystem.Models
@using Nop.Web.Framework;
@using Nop.Web.Framework.UI;


<li class="notification">
    @if (Model.TotalNumberOfUnviewNotification > 0)
        {
            <a href="@UnViewNotificationList" class="ico-notification">
                <span  class="Notification-qty">
                    <img  class="" alt="" src="~/Plugins/Bs.VendorSystem/content/img/notification_icon.png">
                </span>
                <span class="numberOfNotification">@Model.TotalNumberOfUnviewNotification</span>
            </a>
        }
    else
    {
        <a href="@AllNotificationList" class="ico-notification">
            <span style="line-height: 0;" class="Notification-qty">
                <img style="height: 20px; width: 19px;" class="" alt="" src="~/Plugins/Bs.VendorSystem/content/img/notification_icon.png">
            </span>
        </a>
    }
        
</li>

Views/Notification/NotificationListForCustomer.cshtml
@model BsVendorNotificationListModelForCustomer
@using Nop.Core
@using Nop.Core.Domain.Tax
@using Nop.Core.Infrastructure
@using Nop.Plugin.Bs.VendorSystem.Models;
@using Nop.Services.Localization
@using Nop.Web.Framework;
@using Nop.Web.Framework.UI;
@using Nop.Web.Extensions;
@{
    Layout = "~/Views/Shared/_ColumnsOne.cshtml";

    //title
    Html.AddTitleParts(T("PageTitle.Wishlist").Text);
}
<div class="page wishlist-page">
    <div class="page-title">
        <h1>
            @*@T("Wishlist")*@
           @T("Notification.List")
        </h1>
    </div>
    <div class="page-body">
        @if (Model.NotificatioList.Count > 0)
        {
            <div class="wishlist-content">
                @using (Html.BeginRouteForm("Vendor.UnViewNotificationList", FormMethod.Post))
                {
                    <div class="table-wrapper">
                        
                        <table class="cart">
                            <colgroup>
                                <col width="1"/>
                                <col width="1"/>
                                <col/>
                                <col width="1"/>
                            </colgroup>
                            <thead>
                            <tr>
                              
                                <th class="product">
                                    @T("Vendor.Customer")
                                </th>
                                <th class="product">
                                    @T("Vendor.Event")
                                </th>
                                
                                <th class="product">
                                    @T("Vendor.Event.Created.Customer")
                                </th>

                                <th class="product-picture">
                                    @T("ShoppingCart.Image")
                                </th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach (var item in Model.NotificatioList)
                            {
                                if(item.ItemId == 100)
                                {
                                    <tr>
                                        <td class="product">
                                            <a href="@Url.RouteUrl("Product", new {SeName = item.ProductSeName})" class="product-name">@item.ProductName</a>
                                        </td>
                                        <td class="product">
                                            <p class="vendor-name">Product Liked By</p>
                                        </td>
                                        <td class="product">
                                            <p class="vendor-name">@item.NotifierCustomerName</p>
                                        </td>
                                        <td class="product-picture">
                                            <a href="@Url.RouteUrl("Product", new {SeName = item.ProductSeName})"><img alt="@item.Picture.AlternateText" src="@item.Picture.ImageUrl" title="@item.Picture.Title" /></a>
                                        </td>
                                    </tr>
                                }
                                //follow
                                if (item.ItemId == 300)
                                {
                                    <tr>
                                        <td class="product">
                                            <p class="vendor-name">@item.VendorName</p>
                                        </td>
                                        <td class="product">
                                            <p class="vendor-name">Followed Vendor By</p>
                                        </td>
                                        <td class="product">
                                            <p class="vendor-name">@item.NotifierCustomerName</p>
                                        </td>
                                        <td class="product">
                                            <p class="vendor-name"></p>
                                        </td>
                                    </tr>
                                }
                                //Product Add
                                if (item.ItemId == 500)
                                {
                                    <tr>
                                        <td class="product">
                                            <a href="@Url.RouteUrl("Product", new {SeName = item.ProductSeName})" class="product-name">@item.ProductName</a>
                                        </td>
                                        <td class="product">
                                            <p class="vendor-name">Product Added By</p>
                                        </td>
                                        <td class="product">
                                            <p class="vendor-name">@item.NotifierCustomerName</p>
                                        </td>
                                        <td class="product-picture">
                                            <a href="@Url.RouteUrl("Product", new {SeName = item.ProductSeName})"><img alt="@item.Picture.AlternateText" src="@item.Picture.ImageUrl" title="@item.Picture.Title" /></a>
                                        </td>
                                    </tr>
                                }
                                //OrderPlaced
                                if (item.ItemId == 600)
                                {
                                    <tr>
                                        <td class="product">
                                            <a href="@Url.RouteUrl("Product", new {SeName = item.ProductSeName})" class="product-name">@item.ProductName</a>
                                        </td>
                                        <td class="product">
                                            <p class="vendor-name">Order Placed By</p>
                                        </td>
                                        <td class="product">
                                            <p class="vendor-name">@item.NotifierCustomerName</p>
                                        </td>
                                        <td class="product-picture">
                                            <a href="@Url.RouteUrl("Product", new {SeName = item.ProductSeName})"><img alt="@item.Picture.AlternateText" src="@item.Picture.ImageUrl" title="@item.Picture.Title" /></a>
                                        </td>
                                    </tr>
                                }

                            }
                            </tbody>
                        </table>
                    </div>

                    var pager = Html.Pager(Model.PagerModel);
                    if (!MvcHtmlString.IsNullOrEmpty(pager))
                    {
                        <div class="pager">
                            @pager
                        </div>
                    }

                }
            </div>
        }
        else
        {
            <div class="no-data">
                @T("Vendor.ListEmpty")
            </div>
        }
    </div>
</div>